#!/bin/bash
# ICP Research Platform Search Query Generator
# Usage: ./search-platforms.sh <topic> <industry>
# Generates search queries for multiple platforms

TOPIC="${1:-your topic}"
INDUSTRY="${2:-your industry}"

echo "=========================================="
echo "ICP Research Query Templates"
echo "Topic: $TOPIC"
echo "Industry: $INDUSTRY"
echo "=========================================="
echo ""

echo "=== REDDIT QUERIES ==="
echo "site:reddit.com \"$TOPIC\" frustrated OR struggling OR help"
echo "site:reddit.com \"$TOPIC\" recommend OR suggestion OR advice"
echo "site:reddit.com \"$TOPIC\" vs OR alternative OR switch"
echo "site:reddit.com \"$TOPIC\" \"$INDUSTRY\" pain OR problem"
echo "site:reddit.com \"$TOPIC\" review OR experience OR tried"
echo ""

echo "=== TWITTER/X QUERIES ==="
echo "\"$TOPIC\" frustrated -filter:retweets"
echo "\"$TOPIC\" hate OR love OR amazing -filter:retweets"
echo "\"$TOPIC\" recommendation OR suggest lang:en"
echo "\"$TOPIC\" switched from OR moved to"
echo "\"$TOPIC\" $INDUSTRY thread"
echo ""

echo "=== LINKEDIN QUERIES ==="
echo "site:linkedin.com \"$TOPIC\" challenge OR struggle"
echo "site:linkedin.com \"$TOPIC\" lessons OR learned"
echo "site:linkedin.com \"$TOPIC\" \"$INDUSTRY\" tips"
echo ""

echo "=== QUORA QUERIES ==="
echo "site:quora.com \"$TOPIC\" best OR recommend"
echo "site:quora.com \"$TOPIC\" problem OR issue OR frustrated"
echo "site:quora.com \"how to\" \"$TOPIC\" \"$INDUSTRY\""
echo ""

echo "=== YOUTUBE QUERIES ==="
echo "site:youtube.com \"$TOPIC\" review"
echo "site:youtube.com \"$TOPIC\" tutorial beginner"
echo "site:youtube.com \"$TOPIC\" vs"
echo "site:youtube.com \"$TOPIC\" \"$INDUSTRY\" guide"
echo ""

echo "=== G2/CAPTERRA QUERIES ==="
echo "site:g2.com \"$TOPIC\" review"
echo "site:capterra.com \"$TOPIC\" review"
echo "\"$TOPIC\" software review \"what I dislike\""
echo ""

echo "=== FACEBOOK GROUPS QUERIES ==="
echo "site:facebook.com/groups \"$TOPIC\" \"$INDUSTRY\""
echo "\"$TOPIC\" facebook group community"
echo ""

echo "=== DISCORD/COMMUNITY QUERIES ==="
echo "\"$TOPIC\" discord server invite"
echo "\"$TOPIC\" slack community join"
echo "\"$TOPIC\" \"$INDUSTRY\" forum"
echo ""

echo "=== HABITAT DISCOVERY QUERIES ==="
echo "\"$TOPIC\" \"best communities\" OR \"best groups\" OR \"best servers\""
echo "\"$TOPIC\" \"where do you hang out\" OR \"where do you discuss\" OR \"where do you learn\""
echo "\"$TOPIC\" community OR group OR server \"$INDUSTRY\" join OR invite"
echo "\"$TOPIC\" telegram group OR channel \"$INDUSTRY\""
echo "\"$TOPIC\" discord server \"$INDUSTRY\" active"
echo "\"$TOPIC\" subreddit OR \"sub for\" \"$INDUSTRY\""
echo "\"$TOPIC\" \"must-join\" OR \"top communities\" OR \"best places to discuss\""
echo "\"$TOPIC\" \"I found this group\" OR \"check out this server\" OR \"join us on\""
echo ""

echo "=== PAIN POINT QUERIES ==="
echo "\"$TOPIC\" \"I hate when\" OR \"so frustrating\" OR \"drives me crazy\""
echo "\"$TOPIC\" \"wish there was\" OR \"if only\" OR \"would pay for\""
echo "\"$TOPIC\" \"struggling with\" OR \"can't figure out\" OR \"need help with\""
echo "\"$TOPIC\" \"wasted hours\" OR \"wasted money\" OR \"biggest mistake\""
echo ""

echo "=== COMPETITOR RESEARCH QUERIES ==="
echo "\"$TOPIC\" \"switched from\" OR \"moved away from\""
echo "\"$TOPIC\" \"better than\" OR \"instead of\" OR \"alternative to\""
echo "\"$TOPIC\" \"pros and cons\" OR \"honest review\""
echo "\"$TOPIC\" \"not worth it\" OR \"overrated\" OR \"underrated\""
echo ""

echo "=== SUCCESS STORY QUERIES ==="
echo "\"$TOPIC\" \"game changer\" OR \"life saver\" OR \"total transformation\""
echo "\"$TOPIC\" \"finally found\" OR \"wish I knew sooner\""
echo "\"$TOPIC\" \"increased by\" OR \"saved me\" OR \"ROI\""
echo ""

echo "=========================================="
echo "USAGE TIPS:"
echo "1. Run these queries in Google or use WebSearch tool"
echo "2. Sort Reddit results by: controversial, top (all time), new"
echo "3. Look at comment threads, not just top-level posts"
echo "4. Capture exact quotes with platform attribution"
echo "5. Note emotional intensity and frequency patterns"
echo "=========================================="
